### ISSUE TITLE
Groovy mode

### ISSUE THREAD

**Issue by agsiegel** [sinnlabs/zk-codemirror#9]
Include the groovy mode.

**Comment by agsiegel** [comment]
I checked out the code and upgraded the ZK version to 9.6.0.1 and everything compiled fine without any changes.  I can also add the groovy capability.  Can I just perform a pull request?  Thanks.

**Comment by nsa-a1** [comment]
Yep, just create a pull request.Do not modify ZK Version in dependency, because this is a minimum zk version. 10.05.2022, 20:10, "agsiegel" ***@***.***>: I checked out the code and upgraded the ZK version to 9.6.0.1 and everything compiled fine without any changes. I can also add the groovy capability. Can I just perform a pull request? Thanks.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

**Comment by agsiegel** [comment]
WIll you handle the increment of the version number in the lang-addon.xml file?

**Comment by nsa-a1** [comment]
Yep i will increment version, and deploy new release to maven repo23:59, 11 мая 2022 г., agsiegel ***@***.***>:
WIll you handle the increment of the version number in the lang-addon.xml file?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by agsiegel** [comment]
System is not letting me push my branch upstream.  Do you need to give me commit privs on the repo?

**Comment by agsiegel** [comment]
Ok, looks like the pull request went through.  Thanks!!

**Comment by agsiegel** [comment]
Any chance of integrating the pull request soon?  Thanks.

**Comment by nsa-a1** [comment]
you can use the sonatype repo (https://oss.sonatype.org/content/repositories/releases) for the new version 0.8.
README.md file will be updated after synchronization with Maven's repository. This may take a while.
